apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: demo-otel-app-java
  namespace: demo-otel-app
spec:
  # Exporta OTLP para um Collector existente no cluster.
  exporter:
    endpoint: http://alloy.monitoring.svc.cluster.local:4318

  # Mantém HTTP/protobuf (compatível com a maioria dos collectors).
  env:
    - name: OTEL_EXPORTER_OTLP_PROTOCOL
      value: http/protobuf
    - name: OTEL_SERVICE_NAME
      value: demo-otel-app-demo-java
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: deployment.environment=cluster,service.namespace=demo-otel-app
    - name: OTEL_LOGS_EXPORTER
      value: none
    # Correlation logs <-> traces (injeta trace_id/span_id no MDC do Logback)
    - name: OTEL_INSTRUMENTATION_LOGBACK_MDC_ENABLED
      value: "true"
    - name: OTEL_INSTRUMENTATION_RUNTIME_METRICS_ENABLED
      value: "true"


