apiVersion: v1
kind: Service
metadata:
  name: demo-otel-app
  namespace: demo-otel-app
spec:
  type: ClusterIP
  selector:
    app: demo-otel-app
  ports:
    - name: http
      port: 8080
      targetPort: http


