apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: demo-otel
spec:
  type: ClusterIP
  selector:
    app: otel-collector
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
      protocol: TCP
    - name: metrics
      port: 8888
      targetPort: metrics
      protocol: TCP
    - name: prom-metrics
      port: 9464
      targetPort: prom-metrics
      protocol: TCP


