FROM glowroot/glowroot-central:0.14.4

WORKDIR /usr/share/glowroot-central

# Copia configuração customizada do Central
COPY glowroot-central.properties /usr/share/glowroot-central/glowroot-central.properties

EXPOSE 4000


