apiVersion: v1
kind: ConfigMap
metadata:
  name: glowroot-config
  namespace: observability
data:
  glowroot-central.properties: |
    collector.address=0.0.0.0:8181
    ui.bindAddress=0.0.0.0
    ui.port=4000
    log.dir=/usr/share/glowroot-central/logs
    # Formato novo (cassandra.*)
    cassandra.contactPoints=cassandra-client.observability.svc.cluster.local
    cassandra.port=9042
    cassandra.keyspace=glowroot
    cassandra.consistencyLevel=ONE
    cassandra.localDatacenter=dc1
    cassandra.username=
    cassandra.password=
    internal.telemetry.enabled=false
    # Compat: formato antigo (glowroot.storage.cassandra.*) para garantir leitura
    glowroot.storage.cassandra.contactPoints=cassandra-client.observability.svc.cluster.local
    glowroot.storage.cassandra.port=9042
    glowroot.storage.cassandra.keyspace=glowroot
    glowroot.storage.cassandra.consistencyLevel=ONE
    glowroot.storage.cassandra.localDatacenter=dc1
---
apiVersion: v1
kind: Service
metadata:
  name: glowroot-central
  namespace: observability
spec:
  type: ClusterIP
  selector:
    app: glowroot-central
  ports:
    - name: ui
      port: 4000
      targetPort: 4000
    - name: agent
      port: 8181
      targetPort: 8181
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: glowroot-central
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glowroot-central
  template:
    metadata:
      labels:
        app: glowroot-central
    spec:
      securityContext:
        fsGroup: 1000
      tolerations:
        - key: "infra"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      nodeSelector:
        infra: "true"
      containers:
        - name: glowroot-central
          image: glowroot/glowroot-central:0.14.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
              name: ui
            - containerPort: 8181
              name: agent
          volumeMounts:
            - name: config
              mountPath: /usr/share/glowroot-central/glowroot-central.properties
              subPath: glowroot-central.properties
            - name: logs
              mountPath: /usr/share/glowroot-central/logs
          readinessProbe:
            httpGet:
              path: /
              port: ui
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /
              port: ui
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 6
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "2Gi"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            # Evita concentrar múltiplos pods do Glowroot Central no mesmo nó
            # (espalha os pods entre os nodes disponíveis).
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - glowroot-central
                topologyKey: kubernetes.io/hostname
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: glowroot-config
        - name: logs
          emptyDir: {}

